spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/datav?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: 'root'
            password: '123456'
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true


##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/renren_security
#      username: renren
#      password: 123456

    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: localhost
        port: 6379
        password:    # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接

alipay:
    appId: 2021000122628512
    appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCCzPaVaDB9cB3lZzqqSbm4FA3qQefnkmLwU22SWxGnCJ6GwqVkwocvNhMNRbzqByNFAvwNKhggp/+2kyEvVYO0V7qGL9wjg9c8eX1125WnOuS/Ns6ydKkwxv+mY/51u/9hn5De0niggYRZABvIXTllSOcEK1JPIaGAtr7MXeZKexsug0IcMyUzCMSflr0KSNU5oTBH/cKovQS7kRDynnIo9SOZ0TBv7JtZG2mA9CXi89IHc60WcyH5BKT0loLsSc5GKtB+06lnLNvrulesoa75bsTc1y0gZqGIb4VVlK5kMMN4wzw7y3np03P45W2jeEqwmnd9X2J6QhfDIvDhmyJBAgMBAAECggEAM0E/6yINxkm13VwLOAl11jU9kqtKxYqubIA0sqIvE6YkAKiriQVVVeG5q3zFX2t2nadiv4HcPIe4g4G6AkNfPb8W31hHyj7yi8cLq7BlP0ertWYzruhaGDwSl9AdOWN22nldmoMdM8As7XdGa8hkIlVj+VVEhq+mCrsRnyG4iTyLxwNKg6847o5zqJR0GkHUdRR37Wp55CbIjY4uDaJrqQVhy1A8qO68Ff9DWLSmXp0z+JfjSSc2lEgU1sZ6dSuOw4v/sFGFoFKvXx5C21grX99S/bjxOe17EhUO2mWveiwz2zPRXN5n+MrTIbByiok7je+xVSuhQNzX6Yh8HERlMQKBgQDhhQCspIuU+5TV4l/LFd6TF8wmWeQW7Q5KUmbDFTwosyKOr5AgUoKxK1wiA5EAM/Eden0afLyxYgSADdFNl8nJQ5HOhC57Ucaa1nYX8adnzjlNDev/u30eICc3oMDwyPQvD98EkTVlKczlfBuRuJqa+muwNjhe2VeDkRUlJ4sZTQKBgQCUeq12gW+sjJbzGuCNOfIcgIsSn6ykiiR9D8A2uElc5PNXA5Lf1gF3Dj5NzNYAxxvMzlFbS4ZqGG82JfebRWNC35Sy8iuBa+SEjTNnCjoE5eay102ERUZzA3rncgNceaLbF4/jfF/xpjB8FJ9PthNEFJyJ1/wJMi+K/app8E5SxQKBgFXllOYtHkU2te/pc1clE0uvasDIyEm7LRA95oozkmBmKqlyUVEeXE0jGMqT1Szgm9wAhZoLHMvra49is+/7+o3AQM8KJbIu6ZicSwq/rmWpdMXWoaccQIGy+X0Eq7iKsgci4m0Y6d+IVlSqOs38JFcXPuE1Ja9q1Rx1rDokn6SZAoGBAIBOdsF2XsN0Bil0K2G/FiptJkDkvLK/MYLk7owaukLNEj86Nly5OTDhnRNsE+4+IRbdn05OOIxMKyZWrt59mqY6QOxV+yRu0N1+i1Hac4KyDKa1CSZpGtTeyAFi8+agsgu0E8JYQyy2GSXQSE8AnytwyEkR3JkxxgXM6Mt9PqGlAoGAVI06VhhA555GT2QHagmdMOVACK9hnposois403HKlbQ4SbGPBieAn2Jic3eq9EWKxHQbRERZTRgKmehI/4tTR/nTMm9mjJT5fmxHmmTf6tcEEIFLaVC5RbM1fJvcPixfO8JHiGUKp9rlDcEmp4rO9HJle+7/PqIulVz3vm7eQcg=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm0IbX5lYtapNwPjawPS0OOac82yTJMphb5KktP/cHYZss9i9qsn3/JYj+zmODdbkGpe/2+gK57iKUX9X3jOn90eoojIlClcYaRJeSs4y43QsvOmHb5rok779Z7KesK4eHtLCKQU78SrUXiKT76YWFG519GCoHF2yMBMoiRF5yH2DEq6YlnsTHHUdMjJ1WeAiT81c0vCjWzQto1uksH/hY4cov5poNjhWV1POG38JBrCpdybsIwOMU1wkN8Ka2/SA8z3eZU2649mrnBDsOMafbq1wGMS1yRy6oe3xP6AtlUdiIpk909e9b8jWk3IWR5cpWIoVWDSy4R8CAQIR26Df7wIDAQAB
    notifyUrl: http://mj9j6j.natappfree.cc/renren-fast/common/alipay/notify