spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/datav?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: 'root'
            password: '0412'
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true


##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/renren_security
#      username: renren
#      password: 123456

    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: localhost
        port: 6379
        password:    # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接

alipay:
    appId: 9021000134626804
    appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7fLfFmKrYPJv8fkoZ8DHbsoCxpUiAok+i8H4it3bIMJiVhNguP1iIeKuFNQvKc354JPyT2cG7250Ezlw4gLp0A0ksEliH3tsWzbL6hK1CHOhtHw4FlX8/esrnE1xus4ZexMsCZODgFYbPub8M02kvjOiRDAziMq9PFgI/eQ+8f8xYjOkZB6Bl1LJii2/uLgeRjk8DYUhhNIOsttYuRIlWYqQMKt5XZonSWVrEoYUCb/wxudK7EgWFrzKpcqqbhj1nHKKdp09hJpJgVtlkBBlxpSYWwFLdMxi1MMcCPtN8idP2qdYSgD1ASdzSoso+9ezSRGYnw8ucsultFuOM9CbxAgMBAAECggEAae9QTv+yGLg2UvZwnDNRmJdFjBqd2sDbSm+kda1AGmEK9gC3vXnhZkr4by3H2b5kSTJs3IV/p8uw7tRC21IxB/gLUjGTgEH1fO8BH/fzhZWb5nxTiegsnAufte0EnzAkzktXgaTKQxMmtxx2zKJvnoR5q+spJG4LDB6daovWzmRXT4WTKC9Y3rUAqNzOZ6NClHy1GWXv3MI2dA2wdJ8VjFdr3SDIxxEKvm3OPj+cFE43YYFAhJLUBy49phG4nnc9yya7x5Dde5xEb/HrgBhGpGJOcdZlwb1IseAPeayzA4Bct3dXO/XVEyFr9FYHIvtTL/sF41YWXEqo3gctTTxZ2QKBgQDp9Y51cSrCIQd0lY6pG3mxzyZAzOERwAVB+xW3V7Tdhj2/bCFcO/0kfO/ZU9IYTgEpH4LXq8KThtnZhG4gvQhb/bigqs40V3jW0B7ns0Jrbb27HRJYTwUQMkE9npCEIdjW8wr+dL/O35A1u7VJeXeG5okHifuHoMO6029h+bZsvwKBgQDNJmK+1S7WycX1izCv1xNyZWZQ9Ar7h6HplrjGOJvoEs81Qhu/BzngAdONHCac8k4V0G/nnusPUJMV1Z2i0ysugZjxfiyuKeV7NnepOZmpD42ix1E0ck/dL0P6+hl9PlLMwqmfRw0l4M/IGGvQGgbL8EBzqHFafcJgMQqwbkVoTwKBgBOPMuzAnEmEh2IIytd6c48Y+WK7fimEuyvL+QHN9FH80ha5zIQwg7ZUN50cs9jSVKiCeObc9jRtNrNHrglQpG1EZfYQsZKQqYqT9bF7PBdNImqNQKZfXNYAzZGAOybAyacWxJmHWy3JZP4JBlvxKrv9dAFMWNn658IrwQkY3lZzAoGBALf5OIySeZK9F/3/eQX4BsSMEpl+gWrYU2c7dzCsC4SveYr1YhSJ0mkEukbNfAM7eLMvXWuFpJ7zTzRBgUBHx23JYvMOh9sYT2eTjPQBZ7+o5weXX0d9TAm7HWexabJbdb2SxLLF8RCK70suO2FANeAl8GbII/9W0D2bPU7DVRMZAoGAbY+masFHSkAQA6xbPB44SFLL/P/JxZbBvyzMaxG/36kKF33a+5pbhFWwapkj/5dU5mb8dM4wWePtJyDVcRzZZw+pkUm+6B/CvqgD0btOyXGrDjEB+efUPZ3sTS7NofvnZ7U+i7uHGIHamhy3w6fl8vt3BAm1SoiCewFp6OlzBBo=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApq328ikaGB45IwE/aor3O0UB47HSG1wnPEHuL4M2Tvg7t6+dWYyzLiD2JJiv/RvvmsDnTpO0vrhBtL2Z8ttGLTLVyVnIe+Ae4OoMQcLEHPIAAy3i0Y1oC4K+WWCpAmxLhmoUV9wTTSpx2Z8jH4ApIx21XIHYFZoTz8yqSnQstkeQVsSqObUfqDVVsa9jA6Fad4AV77iY4hSjcE2SM0TBv4XttoVGUy5eAlvj0h1GHwqcBk/4YwWumZBZpkllXW3CyjdUHkqxLfvWKxmbRmVmU69dscSAIc4U7C024pjt7hcOjFVN19q7cL45s9eYfpNAzt7JXupKVj109UBcOMfUSwIDAQAB
    notifyUrl: http://d55r7d.natappfree.cc/renren-fast/common/alipay/notify